language: android
jdk:
- oraclejdk8
git:
  submodules: false
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-6
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.3
  - android-24
  - extra-android-m2repository
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install:
- wget https://dl.google.com/android/repository/android-ndk-r13-linux-x86_64.zip -O
  ndk.zip
- unzip -qq ndk.zip
- export ANDROID_NDK_HOME=`pwd`/android-ndk-r13
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
- wget https://github.com/Commit451/android-cmake-installer/releases/download/1.1.0/install-cmake.sh
- chmod +x install-cmake.sh
- "./install-cmake.sh"
before_script:
- export CMAKE_EXECUTABLE=`find ${ANDROID_HOME}cmake/*/bin/cmake`
- mkdir native-build
- cd native-build
- "${CMAKE_EXECUTABLE} -DPLATFORM:STRING=pc ../app/ -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_CC_COMPILER=g++-6"
- cd ..
script:
- "./gradlew build"
- cd native-build
- "${CMAKE_EXECUTABLE} --build ."
- cd ..
deploy:
  provider: releases
  api_key:
    secure: j8Mvgs4ZZy3UZFj3PYNNfBGhyjnCwC/cg2U1IEAkADv4Re5LFnCMii7WWy7WPcmzrzR6fJOb95YpTrbzh1Fpbn00dmVEuQloe4f86mGNyWthI5gU0oRaJwA2VgwN7a9H4RlxXlvQyOt+PVLepxHC28Y2UFl4sI+XX3vNVnX1gtW40ovCYx3VB+6hGrDRUKWuxJj7WS4TNrZc5Pm8mk4l+aSmEXvUrP+LqnczQcCLICuNf6/84mluk9e9BQyFiwlJM+kfq8VeTE5gQUIXjZVhtOsleMiynCmJ+1kKM+8Efs740sT46vmjv5vJ/qsc7/9qcXXgfSbZk86iPXpo5qbZGdqUbVFRyfkGDp50Yme4TkJHkM8nmNoGq/TesWYc6u6VsSJ/H410nh/anA1EO15zGUDpjxDco7mdv7BLj4hg5luBSaM0Vw1EI6+qHwLAXLUExkWVPJ4EVVOOgIXLbnxJoVWoMChUbwPkk4ePBPeiuTjfnRmWdvR/TN19z+tN6ri+GQJ+rSv6bechs0KItdeItK3XZ4NS7yMgvdUDKlXN9JklmxG0SPGsQKWNUnbvgA81EQvhroBOOAOKl7sqImDxXdDoK65QaQ0ZHhB1HVv/XflrbhRIRIv+Mo4klsxp1UnYvXnNBnoHoEYCMeY44K8Zl4Hsw2ee2VuUlZ5QopSWgwE=
  file: native-build/IODkbdServer
  skip_cleanup: true
  on:
    repo: morj/IOTkbd
